# Generated by Django 2.2.16 on 2020-09-20 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_instance',
            name='mostRecentInstance',
        ),
        migrations.AddField(
            model_name='task_instance',
            name='jeffDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
