# Generated by Django 2.2.16 on 2020-09-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychores', '0003_remove_task_instance_jeffdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_instance',
            name='test',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
