# Generated by Django 2.2.16 on 2020-09-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychores', '0004_task_instance_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_instance',
            name='test',
            field=models.BooleanField(default=True),
        ),
    ]
