# Generated by Django 2.2.16 on 2020-09-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychores', '0005_auto_20200920_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_instance',
            old_name='test',
            new_name='isMostRecent',
        ),
    ]
