# Generated by Django 2.2.16 on 2020-09-20 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mychores', '0006_auto_20200920_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_instance',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task_instance',
            name='assignedProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mychores.Profile'),
        ),
        migrations.AlterField(
            model_name='task_instance',
            name='state',
            field=models.CharField(choices=[('u', 'upcoming'), ('d', 'due today'), ('o', 'overdue'), ('p', 'verification pending'), ('e', 'expired'), ('f', 'finished')], default='d', max_length=200),
        ),
        migrations.AlterField(
            model_name='task_instance',
            name='taskTbd',
            field=models.ForeignKey(help_text='What kind of task?', null=True, on_delete=django.db.models.deletion.CASCADE, to='mychores.Task'),
        ),
    ]
