# Generated by Django 2.2.16 on 2020-09-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychores', '0007_auto_20200920_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='state',
        ),
        migrations.AddField(
            model_name='task',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
