# Generated by Django 2.2.16 on 2020-09-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychores', '0008_auto_20200920_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_instance',
            name='currentProjectedScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task_instance',
            name='finishedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
