# Generated by Django 2.2.16 on 2020-09-20 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychores', '0009_auto_20200920_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task_instance',
            name='finishedDate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
