# Generated by Django 2.2.16 on 2020-09-20 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychores', '0012_profile_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.CharField(blank=True, default='No detailed description available', help_text='What needs to be done?', max_length=2000),
        ),
        migrations.AlterField(
            model_name='task_instance',
            name='dueDate',
            field=models.DateField(default=datetime.date(2020, 9, 20)),
        ),
        migrations.AlterField(
            model_name='task_instance',
            name='finishedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task_instance',
            name='notes',
            field=models.CharField(blank=True, default='No notes available', max_length=200),
        ),
    ]
