# Generated by Django 2.2.16 on 2020-09-23 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychores', '0013_auto_20200920_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_instance',
            name='dueDate',
            field=models.DateField(default=datetime.date(2020, 9, 23)),
        ),
    ]
