# Generated by Django 2.2.16 on 2020-11-30 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychores', '0014_auto_20200923_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_instance',
            name='dueDate',
            field=models.DateField(default=datetime.date(2020, 11, 30)),
        ),
    ]
