# Generated by Django 2.2.16 on 2021-01-30 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychores', '0015_auto_20201130_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='isRecurrent',
            field=models.CharField(choices=[('s', 'sporadic'), ('r', 'recurrent'), ('f', 'fixed recurrent')], default='s', help_text='Should the task be repeated in regular time intervals or on demand?', max_length=200),
        ),
        migrations.AlterField(
            model_name='task_instance',
            name='dueDate',
            field=models.DateField(default=datetime.date(2021, 1, 30)),
        ),
    ]
