# Generated by Django 2.2.16 on 2021-01-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychores', '0016_auto_20210130_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_instance',
            name='isMostRecent',
            field=models.BooleanField(default=False),
        ),
    ]
